name: Retrain micro-models every 2h
on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - run: pip install -r requirements.txt

      - name: Train models
        env:
          BINGX_API_KEY:  ${{ secrets.BINGX_API_KEY }}
          BINGX_SECRET_KEY: ${{ secrets.BINGX_SECRET_KEY }}
        run: python scripts/train_all.py

      - name: Check GitHub env
        run: |
          echo "TOKEN=${{ secrets.GITHUB_TOKEN }}"
          echo "REPO=$GITHUB_REPOSITORY"

      - name: Push weights to branch weights
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/upload_weights.py
