name: Walk-forward retrain (2 months)
on:
  schedule:
    - cron: "0 0 1 */2 *"   # 1-е число каждого 2-го месяца
  workflow_dispatch:

permissions:
  contents: write

jobs:
  train:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - run: pip install -r requirements.txt

      - env:
          BINGX_API_KEY: ${{ secrets.BINGX_API_KEY }}
          BINGX_SECRET_KEY: ${{ secrets.BINGX_SECRET_KEY }}
        run: python scripts/train_all.py

        - env:
          GITHUB_TOKEN: ${{ secrets.PAT }} 
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python scripts/upload_weights.py
